[package]
name = "stats"
version = "0.0.1"
authors = ["calixteman <calixte.denizet@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
cpp-parser = { path = ".." }
crossbeam = "0.7"
globset = "0.4"
hashbrown = "0.7"
num_cpus = "1.13"
serde = "1.0"
serde_json = "1.0"